import type {
  AntiMemoryCandidateId,
  AntiMemoryRecordId,
  ActivationDecisionId,
  EmbeddingId,
  EmbeddingModelId,
  EvidenceBundleId,
  EvalCandidateId,
  ExecutionRunId,
  FeedbackDeltaId,
  GoldenCaseId,
  GoldenTaskId,
  MemoryCandidateId,
  MemoryRecordId,
  PolicyGateId,
  ProtectedFailureModeId,
  RetrievalCandidateId,
  RetrievalRunId,
  ReviewAssessmentId,
  SearchDocumentId,
  SourceClaimId,
  SourceDecisionId,
  SourceRejectionId
} from "./ids.js";

type IsAssignable<TValue, TTarget> = [TValue] extends [TTarget] ? true : false;
type IsNotAssignable<TValue, TTarget> =
  IsAssignable<TValue, TTarget> extends true ? false : true;
type Assert<TValue extends true> = TValue;

export type BrandedKrnIdCompatibilityProof = [
  Assert<IsAssignable<string, ExecutionRunId>>,
  Assert<IsAssignable<ExecutionRunId, string>>,
  Assert<IsAssignable<string, EvidenceBundleId>>,
  Assert<IsAssignable<string, ReviewAssessmentId>>,
  Assert<IsAssignable<string, FeedbackDeltaId>>,
  Assert<IsAssignable<string, MemoryRecordId>>,
  Assert<IsAssignable<string, MemoryCandidateId>>,
  Assert<IsAssignable<string, AntiMemoryCandidateId>>,
  Assert<IsAssignable<string, AntiMemoryRecordId>>,
  Assert<IsAssignable<string, SourceClaimId>>,
  Assert<IsAssignable<string, SourceDecisionId>>,
  Assert<IsAssignable<string, SourceRejectionId>>,
  Assert<IsAssignable<string, SearchDocumentId>>,
  Assert<IsAssignable<string, EmbeddingModelId>>,
  Assert<IsAssignable<string, EmbeddingId>>,
  Assert<IsAssignable<string, RetrievalRunId>>,
  Assert<IsAssignable<string, RetrievalCandidateId>>,
  Assert<IsAssignable<string, ActivationDecisionId>>,
  Assert<IsAssignable<string, PolicyGateId>>,
  Assert<IsAssignable<string, EvalCandidateId>>,
  Assert<IsAssignable<string, GoldenTaskId>>,
  Assert<IsAssignable<string, GoldenCaseId>>,
  Assert<IsAssignable<string, ProtectedFailureModeId>>
];

export type BrandedKrnIdSeparationProof = [
  Assert<IsNotAssignable<ExecutionRunId, SourceClaimId>>,
  Assert<IsNotAssignable<SourceClaimId, ExecutionRunId>>,
  Assert<IsNotAssignable<EvidenceBundleId, ReviewAssessmentId>>,
  Assert<IsNotAssignable<ReviewAssessmentId, EvidenceBundleId>>,
  Assert<IsNotAssignable<ReviewAssessmentId, FeedbackDeltaId>>,
  Assert<IsNotAssignable<FeedbackDeltaId, ReviewAssessmentId>>,
  Assert<IsNotAssignable<EvidenceBundleId, FeedbackDeltaId>>,
  Assert<IsNotAssignable<MemoryRecordId, MemoryCandidateId>>,
  Assert<IsNotAssignable<MemoryCandidateId, MemoryRecordId>>,
  Assert<IsNotAssignable<MemoryRecordId, SourceClaimId>>,
  Assert<IsNotAssignable<SourceClaimId, SourceDecisionId>>,
  Assert<IsNotAssignable<SourceDecisionId, SourceClaimId>>,
  Assert<IsNotAssignable<SourceDecisionId, SourceRejectionId>>,
  Assert<IsNotAssignable<SourceRejectionId, SourceDecisionId>>,
  Assert<IsNotAssignable<SearchDocumentId, RetrievalRunId>>,
  Assert<IsNotAssignable<RetrievalRunId, SearchDocumentId>>,
  Assert<IsNotAssignable<RetrievalRunId, RetrievalCandidateId>>,
  Assert<IsNotAssignable<RetrievalCandidateId, RetrievalRunId>>,
  Assert<IsNotAssignable<RetrievalCandidateId, ActivationDecisionId>>,
  Assert<IsNotAssignable<ActivationDecisionId, RetrievalCandidateId>>,
  Assert<IsNotAssignable<SearchDocumentId, EmbeddingId>>,
  Assert<IsNotAssignable<EmbeddingId, SearchDocumentId>>,
  Assert<IsNotAssignable<EmbeddingModelId, EmbeddingId>>,
  Assert<IsNotAssignable<EmbeddingId, EmbeddingModelId>>,
  Assert<IsNotAssignable<PolicyGateId, EvalCandidateId>>,
  Assert<IsNotAssignable<EvalCandidateId, PolicyGateId>>,
  Assert<IsNotAssignable<EvalCandidateId, GoldenTaskId>>,
  Assert<IsNotAssignable<GoldenTaskId, GoldenCaseId>>,
  Assert<IsNotAssignable<GoldenCaseId, ProtectedFailureModeId>>,
  Assert<IsNotAssignable<ProtectedFailureModeId, GoldenCaseId>>,
  Assert<IsNotAssignable<MemoryCandidateId, AntiMemoryCandidateId>>,
  Assert<IsNotAssignable<AntiMemoryCandidateId, MemoryCandidateId>>,
  Assert<IsNotAssignable<AntiMemoryRecordId, MemoryRecordId>>
];
