import type {
  AntiMemoryRecord,
  GoldenTask,
  MemoryRecord,
  TaskContract
} from "@krn/core";
import {
  assessReflectionOutputContract
} from "@krn/core";

import {
  applyActivationFilters,
  applyTemporalFilter,
  assembleContext,
  buildMemoryQuery,
  rankCandidates,
  toMemoryCandidate
} from "./activation/index.js";
import type {
  GoldenBehaviorProof,
  GoldenRunReport
} from "./goldenRunner.js";
import {
  runGoldenTaskFixtures
} from "./goldenRunner.js";

export interface RunKrnBehaviorGoldenGateInput {
  tasks: readonly GoldenTask[];
  now: string;
}

const evidenceRefs = ["packages/harness/src/goldenKrnBehaviorGate.ts"] as const;

const taskContract = (now: string, objective: string): TaskContract => ({
  id: "task-real-behavior-gate",
  operatorIntentId: "intent-real-behavior-gate",
  projectId: "project-1",
  title: "KRN memory behavior regression gate",
  objective,
  constraints: ["use real KRN behavior"],
  nonGoals: ["do not use self-passing Promptfoo smoke"],
  acceptance: ["GoldenTask proof is generated by behavior execution"],
  status: "active",
  metadata: {},
  createdAt: now,
  updatedAt: now
});

const memoryRecord = (overrides: Partial<MemoryRecord>): MemoryRecord => ({
  id: "memory-1",
  projectId: "project-1",
  key: "reviewed-memory",
  kind: "procedure",
  status: "active",
  summary: "Reviewed memory supports safe activation.",
  body: "Memory behavior must be selected only when current and not blocked.",
  owner: "memory-eval",
  confidence: 95,
  applicationGuidance: "Use only when the memory remains current.",
  sourceLineage: [{ sourceId: "source-claim-1" }],
  isUserPreference: false,
  positiveFeedbackCount: 0,
  negativeFeedbackCount: 0,
  metadata: {},
  validFrom: "2026-06-01T00:00:00.000Z",
  createdAt: "2026-06-01T00:00:00.000Z",
  updatedAt: "2026-06-01T00:00:00.000Z",
  ...overrides
});

const antiMemoryRecord = (overrides: Partial<AntiMemoryRecord>): AntiMemoryRecord => ({
  id: "anti-memory-1",
  projectId: "project-1",
  key: "stale-pattern",
  rejectedClaim: "Use stale memory update patterns as trusted guidance.",
  reason: "The pattern was rejected by reviewed anti-memory.",
  invalidatedBySourceClaimIds: [],
  appliesTo: "stale-pattern",
  summary: "Block stale memory pattern.",
  body: "Activation must exclude this stale memory key.",
  owner: "memory-eval",
  confidence: 95,
  sourceLineage: [{ sourceId: "source-claim-anti-memory-1" }],
  metadata: {},
  validFrom: "2026-06-01T00:00:00.000Z",
  createdAt: "2026-06-01T00:00:00.000Z",
  updatedAt: "2026-06-01T00:00:00.000Z",
  ...overrides
});

const proof = (
  caseId: string,
  status: GoldenBehaviorProof["status"],
  summary: string
): GoldenBehaviorProof => ({
  caseId,
  status,
  summary,
  evidenceRefs
});

const runStaleMemoryAbstention = (now: string): GoldenBehaviorProof => {
  const ranked = rankCandidates([
    toMemoryCandidate(memoryRecord({
      id: "memory-smoke-stale",
      confidence: 95,
      validUntil: "2026-06-01T00:00:00.000Z"
    }))
  ], buildMemoryQuery(taskContract(now, "Use the stale memory update pattern.")));
  const context = assembleContext({
    id: "context-real-gate-stale-memory",
    harnessPlanId: "plan-real-gate",
    candidates: applyTemporalFilter(ranked, now),
    createdAt: now
  });
  const staleExclusion = context.exclusions.some((exclusion) =>
    exclusion.subjectId === "memory-smoke-stale" &&
    exclusion.reason === "stale"
  );
  const passed =
    context.status === "abstained" &&
    context.inclusions.length === 0 &&
    staleExclusion;

  return proof(
    "golden-case-memory-smoke-001",
    passed ? "passed" : "failed",
    passed
      ? "Real activation behavior abstained on stale memory and produced stale exclusion."
      : "Real activation behavior did not abstain on stale memory with stale exclusion."
  );
};

const runAntiMemoryBlock = (now: string): GoldenBehaviorProof => {
  const ranked = rankCandidates([
    toMemoryCandidate(memoryRecord({
      id: "memory-stale-pattern",
      key: "stale-pattern",
      summary: "Stale pattern appears highly relevant for memory updates.",
      body: "This stale pattern should be tempting but blocked.",
      confidence: 98
    }))
  ], buildMemoryQuery(taskContract(now, "Use stale pattern guidance for a memory update.")));
  const filtered = applyActivationFilters({
    candidates: ranked,
    antiMemoryRecords: [antiMemoryRecord({})],
    minimumTrustTier: "low",
    now
  });
  const context = assembleContext({
    id: "context-real-gate-anti-memory",
    harnessPlanId: "plan-real-gate",
    candidates: filtered.candidates,
    createdAt: now
  });
  const unsafeExclusion = context.exclusions.some((exclusion) =>
    exclusion.subjectId === "memory-stale-pattern" &&
    exclusion.reason === "unsafe"
  );
  const conflict = filtered.conflictSets.some((conflictSet) =>
    conflictSet.reason === "anti_memory_block" &&
    conflictSet.candidateIds.includes("memory-stale-pattern") &&
    conflictSet.candidateIds.includes("anti-memory-1")
  );
  const passed =
    context.inclusions.length === 0 &&
    unsafeExclusion &&
    conflict;

  return proof(
    "golden-case-memory-smoke-002",
    passed ? "passed" : "failed",
    passed
      ? "Real activation behavior blocked memory-stale-pattern with anti-memory conflict evidence."
      : "Real activation behavior did not block memory-stale-pattern with anti-memory conflict evidence."
  );
};

const runReflectionFinalTruthBlock = (now: string): GoldenBehaviorProof => {
  const assessment = assessReflectionOutputContract({
    candidateLinks: [{
      targetType: "memory_record"
    }],
    metadata: {
      checkedAt: now
    }
  });
  const passed =
    !assessment.candidateOnly &&
    assessment.violations.some((violation) =>
      violation.path === "candidateLinks.0.targetType" &&
      violation.reason === "final_truth_target" &&
      violation.value === "memory_record"
    );

  return proof(
    "golden-case-reflection-001-a",
    passed ? "passed" : "failed",
    passed
      ? "Real reflection behavior blocked final MemoryRecord target generation."
      : "Real reflection behavior did not block final MemoryRecord target generation."
  );
};

const proofFactories = {
  "golden-case-memory-smoke-001": runStaleMemoryAbstention,
  "golden-case-memory-smoke-002": runAntiMemoryBlock,
  "golden-case-reflection-001-a": runReflectionFinalTruthBlock
} as const;

type SupportedCaseId = keyof typeof proofFactories;

const isSupportedCaseId = (caseId: string): caseId is SupportedCaseId =>
  caseId in proofFactories;

export const runKrnBehaviorGoldenGate = (
  input: RunKrnBehaviorGoldenGateInput
): GoldenRunReport => {
  const caseIds = new Set(
    input.tasks.flatMap((task) => task.cases.map((goldenCase) => goldenCase.id))
  );
  const proofs = [...caseIds].flatMap((caseId) =>
    isSupportedCaseId(caseId) ? [proofFactories[caseId](input.now)] : []
  );

  return runGoldenTaskFixtures({
    tasks: input.tasks,
    proofs
  });
};
