import type {
  AntiMemoryRecord,
  GoldenTask,
  MemoryRecord,
  ObservationItem,
  SourceClaim,
  TaskContract
} from "@krn/core";
import {
  assessReflectionOutputContract,
  normalizeEvidenceCommand
} from "@krn/core";

import {
  applyActivationFilters,
  applyContextROI,
  applyTemporalFilter,
  assembleContext,
  buildActivationRawRecallTriggers,
  buildMemoryQuery,
  buildSourceQuery,
  rankCandidates,
  toMemoryCandidate,
  toSourceClaimCandidate
} from "./activation/index.js";
import type {
  GoldenBehaviorProof,
  GoldenRunReport
} from "./goldenRunner.js";
import {
  runGoldenTaskFixtures
} from "./goldenRunner.js";
import {
  selectObservationPrefix
} from "./observations/observationPrefix.js";

export interface RunKrnBehaviorGoldenGateInput {
  tasks: readonly GoldenTask[];
  now: string;
}

const evidenceRefs = ["packages/harness/src/goldenKrnBehaviorGate.ts"] as const;

const taskContract = (now: string, objective: string): TaskContract => ({
  id: "task-real-behavior-gate",
  operatorIntentId: "intent-real-behavior-gate",
  projectId: "project-1",
  title: "KRN memory behavior regression gate",
  objective,
  constraints: ["use real KRN behavior"],
  nonGoals: ["do not use self-passing Promptfoo smoke"],
  acceptance: ["GoldenTask proof is generated by behavior execution"],
  status: "active",
  metadata: {},
  createdAt: now,
  updatedAt: now
});

const memoryRecord = (overrides: Partial<MemoryRecord>): MemoryRecord => ({
  id: "memory-1",
  projectId: "project-1",
  key: "reviewed-memory",
  kind: "procedure",
  status: "active",
  summary: "Reviewed memory supports safe activation.",
  body: "Memory behavior must be selected only when current and not blocked.",
  owner: "memory-eval",
  confidence: 95,
  applicationGuidance: "Use only when the memory remains current.",
  sourceLineage: [{ sourceId: "source-claim-1" }],
  isUserPreference: false,
  positiveFeedbackCount: 0,
  negativeFeedbackCount: 0,
  metadata: {},
  validFrom: "2026-06-01T00:00:00.000Z",
  createdAt: "2026-06-01T00:00:00.000Z",
  updatedAt: "2026-06-01T00:00:00.000Z",
  ...overrides
});

const antiMemoryRecord = (overrides: Partial<AntiMemoryRecord>): AntiMemoryRecord => ({
  id: "anti-memory-1",
  projectId: "project-1",
  key: "stale-pattern",
  rejectedClaim: "Use stale memory update patterns as trusted guidance.",
  reason: "The pattern was rejected by reviewed anti-memory.",
  invalidatedBySourceClaimIds: [],
  appliesTo: "stale-pattern",
  summary: "Block stale memory pattern.",
  body: "Activation must exclude this stale memory key.",
  owner: "memory-eval",
  confidence: 95,
  sourceLineage: [{ sourceId: "source-claim-anti-memory-1" }],
  metadata: {},
  validFrom: "2026-06-01T00:00:00.000Z",
  createdAt: "2026-06-01T00:00:00.000Z",
  updatedAt: "2026-06-01T00:00:00.000Z",
  ...overrides
});

const sourceClaim = (overrides: Partial<SourceClaim>): SourceClaim => ({
  id: "source-claim-exact-proof",
  sourceArtifactId: "source-artifact-1",
  claim: "Exact source proof is required before using this activation claim.",
  mechanism: "The claim affects implementation safety and needs raw evidence recall.",
  krnImplication: "Activation may include the claim only with a raw recall trigger.",
  doesNotProve: "This does not prove implementation correctness.",
  trustTier: "high",
  supportType: "supports",
  consumer: "golden-real-behavior-gate",
  status: "proposed",
  metadata: {},
  createdAt: "2026-06-01T00:00:00.000Z",
  updatedAt: "2026-06-01T00:00:00.000Z",
  ...overrides
});

const observationItem = (now: string, overrides: Partial<ObservationItem>): ObservationItem => ({
  id: "observation-unsourced-prefix",
  groupId: "observation-group-1",
  scope: {
    projectId: "project-1",
    taskContractId: "task-real-behavior-gate"
  },
  kind: "fact",
  status: "candidate",
  priority: "high",
  confidence: "high",
  provenanceKind: "run_event",
  subject: "observation prefix source range",
  summary: "Observation prefix source range is required.",
  body: "Activation must reject selected observation prefix items without source ranges.",
  temporalScope: {
    observedAt: now,
    ingestedAt: now,
    validFrom: now
  },
  sourceRanges: [{
    id: "observation-range-1",
    sourceType: "run_event",
    sourceId: "run-event-1",
    locator: "run_events.sequence:1",
    capturedAt: now
  }],
  entityLinks: [],
  claimLinks: [],
  metadata: {},
  createdAt: now,
  updatedAt: now,
  ...overrides
});

const proof = (
  caseId: string,
  status: GoldenBehaviorProof["status"],
  summary: string
): GoldenBehaviorProof => ({
  caseId,
  status,
  provenance: "krn_behavior_execution",
  summary,
  evidenceRefs,
  doesNotProve:
    "This behavior proof does not prove Promptfoo smoke executes KRN behavior or that Memory Brain is globally ready."
});

const runStaleMemoryAbstention = (now: string): GoldenBehaviorProof => {
  const ranked = rankCandidates([
    toMemoryCandidate(memoryRecord({
      id: "memory-smoke-stale",
      confidence: 95,
      validUntil: "2026-06-01T00:00:00.000Z"
    }))
  ], buildMemoryQuery(taskContract(now, "Use the stale memory update pattern.")));
  const context = assembleContext({
    id: "context-real-gate-stale-memory",
    harnessPlanId: "plan-real-gate",
    candidates: applyTemporalFilter(ranked, now),
    createdAt: now
  });
  const staleExclusion = context.exclusions.some((exclusion) =>
    exclusion.subjectId === "memory-smoke-stale" &&
    exclusion.reason === "stale"
  );
  const passed =
    context.status === "abstained" &&
    context.inclusions.length === 0 &&
    staleExclusion;

  return proof(
    "golden-case-memory-smoke-001",
    passed ? "passed" : "failed",
    passed
      ? "Real activation behavior abstained on stale memory and produced stale exclusion."
      : "Real activation behavior did not abstain on stale memory with stale exclusion."
  );
};

const runAntiMemoryBlock = (now: string): GoldenBehaviorProof => {
  const ranked = rankCandidates([
    toMemoryCandidate(memoryRecord({
      id: "memory-stale-pattern",
      key: "stale-pattern",
      summary: "Stale pattern appears highly relevant for memory updates.",
      body: "This stale pattern should be tempting but blocked.",
      confidence: 98
    }))
  ], buildMemoryQuery(taskContract(now, "Use stale pattern guidance for a memory update.")));
  const filtered = applyActivationFilters({
    candidates: ranked,
    antiMemoryRecords: [antiMemoryRecord({})],
    minimumTrustTier: "low",
    now
  });
  const context = assembleContext({
    id: "context-real-gate-anti-memory",
    harnessPlanId: "plan-real-gate",
    candidates: filtered.candidates,
    createdAt: now
  });
  const unsafeExclusion = context.exclusions.some((exclusion) =>
    exclusion.subjectId === "memory-stale-pattern" &&
    exclusion.reason === "unsafe"
  );
  const conflict = filtered.conflictSets.some((conflictSet) =>
    conflictSet.reason === "anti_memory_block" &&
    conflictSet.candidateIds.includes("memory-stale-pattern") &&
    conflictSet.candidateIds.includes("anti-memory-1")
  );
  const passed =
    context.inclusions.length === 0 &&
    unsafeExclusion &&
    conflict;

  return proof(
    "golden-case-memory-smoke-002",
    passed ? "passed" : "failed",
    passed
      ? "Real activation behavior blocked memory-stale-pattern with anti-memory conflict evidence."
      : "Real activation behavior did not block memory-stale-pattern with anti-memory conflict evidence."
  );
};

const runReflectionFinalTruthBlock = (now: string): GoldenBehaviorProof => {
  const assessment = assessReflectionOutputContract({
    candidateLinks: [{
      targetType: "memory_record"
    }],
    metadata: {
      checkedAt: now
    }
  });
  const passed =
    !assessment.candidateOnly &&
    assessment.violations.some((violation) =>
      violation.path === "candidateLinks.0.targetType" &&
      violation.reason === "final_truth_target" &&
      violation.value === "memory_record"
    );

  return proof(
    "golden-case-reflection-001-a",
    passed ? "passed" : "failed",
    passed
      ? "Real reflection behavior blocked final MemoryRecord target generation."
      : "Real reflection behavior did not block final MemoryRecord target generation."
  );
};

const runRawRecallExactProof = (now: string): GoldenBehaviorProof => {
  const ranked = rankCandidates([
    toSourceClaimCandidate(sourceClaim({}))
  ], buildSourceQuery(taskContract(now, "Use exact source proof before implementing activation safety.")));
  const context = assembleContext({
    id: "context-real-gate-exact-proof",
    harnessPlanId: "plan-real-gate",
    candidates: applyContextROI(ranked, { maxInclusions: 1 }),
    createdAt: now
  });
  const triggers = buildActivationRawRecallTriggers({
    candidates: ranked,
    contextAssembly: context,
    requireExactProof: true
  });
  const passed =
    context.inclusions.some((inclusion) =>
      inclusion.subjectType === "source_claim" &&
      inclusion.subjectId === "source-claim-exact-proof"
    ) &&
    triggers.some((trigger) =>
      trigger.subjectType === "source_claim" &&
      trigger.subjectId === "source-claim-exact-proof" &&
      trigger.reasons.includes("exact_proof_required") &&
      trigger.evidenceHints.includes("source_claim:source-claim-exact-proof")
    );

  return proof(
    "golden-case-memory-005-a",
    passed ? "passed" : "failed",
    passed
      ? "Real activation behavior included exact-proof source claim only with raw recall trigger."
      : "Real activation behavior did not attach raw recall trigger to exact-proof source claim."
  );
};

const runObservationPrefixSourceRangeRejection = (now: string): GoldenBehaviorProof => {
  const task = taskContract(
    now,
    "Use observation prefix source range evidence before assembling context."
  );
  const prefix = selectObservationPrefix({
    task,
    projectId: "project-1",
    observations: [observationItem(now, {
      sourceRanges: []
    })],
    maxItems: 1,
    now
  });
  const context = assembleContext({
    id: "context-real-gate-unsourced-prefix",
    harnessPlanId: "plan-real-gate",
    candidates: [],
    observationPrefix: prefix,
    createdAt: now
  });
  const passed =
    context.status === "abstained" &&
    context.observationPrefix === undefined &&
    context.observationPrefixGate?.status === "rejected" &&
    context.observationPrefixGate.reasons.includes("missing_source_ranges") &&
    context.observationPrefixGate.rejectedObservationIds.includes("observation-unsourced-prefix");

  return proof(
    "golden-case-observation-prefix-001-a",
    passed ? "passed" : "failed",
    passed
      ? "Real context assembly rejected selected observation prefix item without source ranges."
      : "Real context assembly did not reject selected observation prefix item without source ranges."
  );
};

const runEvidenceCommandProvenance = (_now: string): GoldenBehaviorProof => {
  const weakDefault = normalizeEvidenceCommand({
    command: "pnpm test",
    status: "not_run"
  });
  const operatorReported = normalizeEvidenceCommand({
    command: "pnpm typecheck",
    status: "passed",
    provenance: "operator_reported",
    exitCode: 0,
    capturedAt: "2026-06-23T10:00:00.000Z",
    assertedBy: "operator"
  });
  const passed =
    weakDefault.provenance === "default_template" &&
    weakDefault.status === "not_run" &&
    weakDefault.doesNotProve.includes("does not prove the command executed") &&
    operatorReported.provenance === "operator_reported" &&
    operatorReported.status === "passed" &&
    operatorReported.doesNotProve.includes("does not prove memory quality");

  return proof(
    "golden-case-evidence-001-a",
    passed ? "passed" : "failed",
    passed
      ? "Real EvidenceBundle behavior distinguishes weak default command rows from operator-reported passed evidence."
      : "Real EvidenceBundle behavior did not preserve command provenance distinction."
  );
};

const proofFactories = {
  "golden-case-memory-smoke-001": runStaleMemoryAbstention,
  "golden-case-memory-smoke-002": runAntiMemoryBlock,
  "golden-case-reflection-001-a": runReflectionFinalTruthBlock,
  "golden-case-memory-005-a": runRawRecallExactProof,
  "golden-case-observation-prefix-001-a": runObservationPrefixSourceRangeRejection,
  "golden-case-evidence-001-a": runEvidenceCommandProvenance
} as const;

type SupportedCaseId = keyof typeof proofFactories;

const isSupportedCaseId = (caseId: string): caseId is SupportedCaseId =>
  caseId in proofFactories;

export const runKrnBehaviorGoldenGate = (
  input: RunKrnBehaviorGoldenGateInput
): GoldenRunReport => {
  const caseIds = new Set(
    input.tasks.flatMap((task) => task.cases.map((goldenCase) => goldenCase.id))
  );
  const proofs = [...caseIds].flatMap((caseId) =>
    isSupportedCaseId(caseId) ? [proofFactories[caseId](input.now)] : []
  );

  return runGoldenTaskFixtures({
    tasks: input.tasks,
    proofs
  });
};
