import type {
  AntiMemoryRecord,
  BehaviorFixture,
  MemoryRecord,
  ObservationItem,
  ExtractionClaimCandidate,
  SourceClaim,
  SourceClaimEdge,
  TaskContract
} from "@krn/core";
import {
  assessSourceClaimReviewSignals,
  assessReflectionOutputContract,
  buildSourceArtifactPreviewChunks,
  extractLocalSourceCandidates,
  toEvidenceCommandReadback,
  sourceArtifactLines
} from "@krn/core";

import {
  applyActivationFilters,
  applyContextROI,
  applySourceClaimEdgeInfluence,
  applyTemporalFilter,
  assembleContext,
  buildActivationRawRecallTriggers,
  buildOwnerFileRecallCandidates,
  buildMemoryQuery,
  buildRelationGroundedQaReadback,
  buildSourceQuery,
  rankCandidates,
  toMemoryCandidate,
  toSourceClaimCandidate
} from "./activation/index.js";
import type {
  BehaviorFixtureProof,
  BehaviorFixtureRunReport
} from "./behavior-fixture-runner.js";
import {
  runBehaviorFixtures
} from "./behavior-fixture-runner.js";
import {
  selectObservationPrefix
} from "./observations/observation-prefix.js";
import type {
  TargetActivationTrustExclusion,
  TargetActivationReadModel
} from "./activation/owner-file-recall.js";
import type {
  ActivationCandidate
} from "./activation/types.js";

export interface RunKrnBehaviorGateInput {
  tasks: readonly BehaviorFixture[];
  now: string;
}

const evidenceRefs = ["packages/harness/src/krn-behavior-gate.ts"] as const;

const defaultTargetTrustExclusions = (): TargetActivationTrustExclusion[] => [
  {
    pathPattern: ".env*",
    reason: "secret-shaped environment files must not enter planning context"
  },
  {
    pathPattern: ".git/",
    reason: "repository internals are not planning source truth"
  },
  {
    pathPattern: "node_modules/",
    reason: "third-party install output is not target source truth"
  },
  {
    pathPattern: ".muke/",
    reason: "generated target state is not source truth by default"
  },
  {
    pathPattern: ".supersearch/runtime/",
    reason: "runtime search output is generated state"
  },
  {
    pathPattern: "dist/",
    reason: "build output is generated state"
  },
  {
    pathPattern: "build/",
    reason: "build output is generated state"
  }
];

const hasPathPattern = (value: unknown, pathPattern: string): boolean =>
  typeof value === "object" &&
  value !== null &&
  "pathPattern" in value &&
  value.pathPattern === pathPattern;

const hasTrustExclusionPatterns = (
  value: unknown,
  requiredPatterns: readonly string[]
): boolean =>
  Array.isArray(value) &&
  requiredPatterns.every((pathPattern) =>
    value.some((pattern) => hasPathPattern(pattern, pathPattern))
  );

const buildTargetRecallState = (
  now: string,
  objective: string,
  readModel: TargetActivationReadModel
) => {
  const candidates = buildOwnerFileRecallCandidates(
    taskContract(now, objective),
    { targetReadModel: readModel }
  );
  const trustExclusionCandidate = candidates.find((candidate) =>
    candidate.metadata.targetReadModelKind === "trust_exclusions"
  );

  return {
    candidates,
    trustExclusionPatterns: trustExclusionCandidate?.metadata.trustExclusions,
    hasTrustExclusionCandidate: trustExclusionCandidate !== undefined,
    staticKrnOwnerFileSelected: candidates.some((candidate) =>
      candidate.metadata.source === "owner_file_recall"
    )
  };
};

const hasSourceSeedPath = (
  candidates: ReturnType<typeof buildOwnerFileRecallCandidates>,
  path: string
): boolean =>
  candidates.some((candidate) =>
    candidate.metadata.targetReadModelKind === "source_seed" &&
    candidate.metadata.targetPath === path
  );

const sourceSeedPaths = (
  candidates: ReturnType<typeof buildOwnerFileRecallCandidates>
): unknown[] =>
  candidates
    .filter((candidate) => candidate.metadata.targetReadModelKind === "source_seed")
    .map((candidate) => candidate.metadata.targetPath);

const taskContract = (now: string, objective: string): TaskContract => ({
  id: "task-real-behavior-gate",
  operatorIntentId: "intent-real-behavior-gate",
  projectId: "project-1",
  title: "KRN memory behavior regression gate",
  objective,
  constraints: ["use real KRN behavior"],
  nonGoals: ["do not use self-passing Promptfoo smoke"],
  acceptance: ["BehaviorFixture proof is generated by behavior execution"],
  status: "active",
  metadata: {},
  createdAt: now,
  updatedAt: now
});

const memoryRecord = (overrides: Partial<MemoryRecord>): MemoryRecord => ({
  id: "memory-1",
  projectId: "project-1",
  key: "reviewed-memory",
  kind: "procedure",
  status: "active",
  summary: "Reviewed memory supports safe activation.",
  body: "Memory behavior must be selected only when current and not blocked.",
  owner: "memory-eval",
  confidence: 95,
  applicationGuidance: "Use only when the memory remains current.",
  sourceLineage: [{ sourceId: "source-claim-1" }],
  isUserPreference: false,
  positiveFeedbackCount: 0,
  negativeFeedbackCount: 0,
  metadata: {},
  validFrom: "2026-06-01T00:00:00.000Z",
  createdAt: "2026-06-01T00:00:00.000Z",
  updatedAt: "2026-06-01T00:00:00.000Z",
  ...overrides
});

const antiMemoryRecord = (overrides: Partial<AntiMemoryRecord>): AntiMemoryRecord => ({
  id: "anti-memory-1",
  projectId: "project-1",
  key: "stale-knowledge",
  rejectedClaim: "Use stale memory update procedures as trusted guidance.",
  reason: "The knowledge was rejected by reviewed anti-memory.",
  invalidatedBySourceClaimIds: [],
  appliesTo: "stale-knowledge",
  summary: "Block stale memory knowledge.",
  body: "Activation must exclude this stale memory key.",
  owner: "memory-eval",
  confidence: 95,
  sourceLineage: [{ sourceId: "source-claim-anti-memory-1" }],
  metadata: {},
  validFrom: "2026-06-01T00:00:00.000Z",
  createdAt: "2026-06-01T00:00:00.000Z",
  updatedAt: "2026-06-01T00:00:00.000Z",
  ...overrides
});

const sourceClaim = (overrides: Partial<SourceClaim>): SourceClaim => ({
  id: "source-claim-exact-proof",
  sourceArtifactId: "source-artifact-1",
  claim: "Exact source proof is required before using this activation claim.",
  mechanism: "The claim affects implementation safety and needs raw evidence recall.",
  krnImplication: "Activation may include the claim only with a raw recall trigger.",
  doesNotProve: "This does not prove implementation correctness.",
  sourceAuthority: "high",
  supportType: "supports",
  consumer: "golden-real-behavior-gate",
  status: "accepted",
  metadata: {},
  createdAt: "2026-06-01T00:00:00.000Z",
  updatedAt: "2026-06-01T00:00:00.000Z",
  ...overrides
});

const observationItem = (now: string, overrides: Partial<ObservationItem>): ObservationItem => ({
  id: "observation-unsourced-prefix",
  groupId: "observation-group-1",
  scope: {
    projectId: "project-1",
    taskContractId: "task-real-behavior-gate"
  },
  kind: "fact",
  status: "candidate",
  priority: "high",
  confidence: "high",
  provenanceKind: "run_event",
  subject: "observation prefix source range",
  summary: "Observation prefix source range is required.",
  body: "Activation must reject selected observation prefix items without source ranges.",
  temporalScope: {
    observedAt: now,
    ingestedAt: now,
    validFrom: now
  },
  sourceRanges: [{
    id: "observation-range-1",
    sourceType: "run_event",
    sourceId: "run-event-1",
    locator: "run_events.sequence:1",
    capturedAt: now
  }],
  entityLinks: [],
  claimLinks: [],
  metadata: {},
  createdAt: now,
  updatedAt: now,
  ...overrides
});

export interface ClaimedCodexOutputEvidence {
  readonly summary?: unknown;
  readonly claimsKrnContextUse?: unknown;
  readonly evidenceRefs?: unknown;
  readonly verification?: unknown;
  readonly changedFiles?: unknown;
  readonly doesNotProve?: unknown;
}

const nonEmptyStringArray = (
  value: unknown
): readonly string[] | undefined =>
  Array.isArray(value) &&
  value.length > 0 &&
  value.every((item) => typeof item === "string" && item.trim().length > 0)
    ? value
    : undefined;

export const validateClaimedCodexOutputEvidence = (
  output: ClaimedCodexOutputEvidence
): readonly string[] => {
  const findings: string[] = [];

  if (typeof output.summary !== "string" || output.summary.trim().length === 0) {
    findings.push("summary is required");
  }

  if (output.claimsKrnContextUse !== true) {
    findings.push("claimsKrnContextUse=true is required for KRN-followed output claims");
  }

  if (nonEmptyStringArray(output.evidenceRefs) === undefined) {
    findings.push("evidenceRefs are required for claimed KRN output evidence");
  }

  if (nonEmptyStringArray(output.verification) === undefined) {
    findings.push("verification evidence is required for claimed KRN output evidence");
  }

  if (nonEmptyStringArray(output.changedFiles) === undefined) {
    findings.push("changedFiles are required for claimed KRN output evidence");
  }

  if (typeof output.doesNotProve !== "string" || output.doesNotProve.trim().length === 0) {
    findings.push("doesNotProve is required for claimed KRN output evidence");
  }

  return findings;
};

const proof = (
  caseId: string,
  status: BehaviorFixtureProof["status"],
  summary: string
): BehaviorFixtureProof => ({
  caseId,
  status,
  provenance: "krn_behavior_execution",
  summary,
  evidenceRefs,
  doesNotProve:
    "This behavior proof does not prove Promptfoo smoke executes KRN behavior or that Memory Brain is globally ready."
});

const runStaleMemoryAbstention = (now: string): BehaviorFixtureProof => {
  const ranked = rankCandidates([
    toMemoryCandidate(memoryRecord({
      id: "memory-smoke-stale",
      confidence: 95,
      validUntil: "2026-06-01T00:00:00.000Z"
    }))
  ], buildMemoryQuery(taskContract(now, "Use the stale memory update procedure.")));
  const context = assembleContext({
    id: "context-real-gate-stale-memory",
    harnessPlanId: "plan-real-gate",
    candidates: applyTemporalFilter(ranked, now),
    createdAt: now
  });
  const staleExclusion = context.exclusions.some((exclusion) =>
    exclusion.subjectId === "memory-smoke-stale" &&
    exclusion.reason === "stale"
  );
  const passed =
    context.status === "abstained" &&
    context.inclusions.length === 0 &&
    staleExclusion;

  return proof(
    "golden-case-memory-smoke-001",
    passed ? "passed" : "failed",
    passed
      ? "Real activation behavior abstained on stale memory and produced stale exclusion."
      : "Real activation behavior did not abstain on stale memory with stale exclusion."
  );
};

const runAntiMemoryBlock = (now: string): BehaviorFixtureProof => {
  const ranked = rankCandidates([
    toMemoryCandidate(memoryRecord({
      id: "memory-stale-knowledge",
      key: "stale-knowledge",
      summary: "Stale knowledge appears highly relevant for memory updates.",
      body: "This stale knowledge should be tempting but blocked.",
      confidence: 98
    }))
  ], buildMemoryQuery(taskContract(now, "Use stale knowledge guidance for a memory update.")));
  const filtered = applyActivationFilters({
    candidates: ranked,
    antiMemoryRecords: [antiMemoryRecord({})],
    minimumSourceAuthority: "low",
    now
  });
  const context = assembleContext({
    id: "context-real-gate-anti-memory",
    harnessPlanId: "plan-real-gate",
    candidates: filtered.candidates,
    createdAt: now
  });
  const unsafeExclusion = context.exclusions.some((exclusion) =>
    exclusion.subjectId === "memory-stale-knowledge" &&
    exclusion.reason === "unsafe"
  );
  const conflict = filtered.conflictSets.some((conflictSet) =>
    conflictSet.reason === "anti_memory_block" &&
    conflictSet.candidateIds.includes("memory-stale-knowledge") &&
    conflictSet.candidateIds.includes("anti-memory-1")
  );
  const passed =
    context.inclusions.length === 0 &&
    unsafeExclusion &&
    conflict;

  return proof(
    "golden-case-memory-smoke-002",
    passed ? "passed" : "failed",
    passed
      ? "Real activation behavior blocked memory-stale-knowledge with anti-memory conflict evidence."
      : "Real activation behavior did not block memory-stale-knowledge with anti-memory conflict evidence."
  );
};

const runReflectionNonCandidateTargetBlock = (now: string): BehaviorFixtureProof => {
  const assessment = assessReflectionOutputContract({
    candidateLinks: [{
      targetType: "memory_record"
    }],
    metadata: {
      checkedAt: now
    }
  });
  const passed =
    !assessment.candidateOnly &&
    assessment.violations.some((violation) =>
      violation.path === "candidateLinks.0.targetType" &&
      violation.reason === "non_candidate_target" &&
      violation.value === "memory_record"
    );

  return proof(
    "golden-case-reflection-001-a",
    passed ? "passed" : "failed",
    passed
      ? "Real reflection behavior blocked direct MemoryRecord target generation."
      : "Real reflection behavior did not block direct MemoryRecord target generation."
  );
};

const runRawRecallExactProof = (now: string): BehaviorFixtureProof => {
  const ranked = rankCandidates([
    toSourceClaimCandidate(sourceClaim({}))
  ], buildSourceQuery(taskContract(now, "Use exact source proof before implementing activation safety.")));
  const context = assembleContext({
    id: "context-real-gate-exact-proof",
    harnessPlanId: "plan-real-gate",
    candidates: applyContextROI(ranked, { maxInclusions: 1 }),
    createdAt: now
  });
  const triggers = buildActivationRawRecallTriggers({
    candidates: ranked,
    contextAssembly: context,
    requireExactProof: true
  });
  const passed =
    context.inclusions.some((inclusion) =>
      inclusion.subjectType === "source_claim" &&
      inclusion.subjectId === "source-claim-exact-proof"
    ) &&
    triggers.some((trigger) =>
      trigger.subjectType === "source_claim" &&
      trigger.subjectId === "source-claim-exact-proof" &&
      trigger.reasons.includes("exact_proof_required") &&
      trigger.evidenceHints.includes("source_claim:source-claim-exact-proof")
    );

  return proof(
    "golden-case-memory-005-a",
    passed ? "passed" : "failed",
    passed
      ? "Real activation behavior included exact-proof source claim only with raw recall trigger."
      : "Real activation behavior did not attach raw recall trigger to exact-proof source claim."
  );
};

const runContextRoiBoundary = (now: string): BehaviorFixtureProof => {
  const ranked = rankCandidates([
    toMemoryCandidate(memoryRecord({
      id: "memory-context-primary",
      summary: "Context ROI must keep Codex brief context small.",
      applicationGuidance: "Use this as the selected bounded context item."
    })),
    toMemoryCandidate(memoryRecord({
      id: "memory-context-extra-1",
      summary: "Extra context item that should stay excluded.",
      applicationGuidance: "Use only if the primary context is insufficient."
    })),
    toMemoryCandidate(memoryRecord({
      id: "memory-context-extra-2",
      summary: "Another extra context item that should stay excluded.",
      applicationGuidance: "Use only if more context is explicitly required."
    }))
  ], buildMemoryQuery(taskContract(now, "Assemble a small Codex brief context packet.")));
  const context = assembleContext({
    id: "context-real-gate-context-roi",
    harnessPlanId: "plan-real-gate",
    candidates: applyContextROI(ranked, {
      maxInclusions: 1,
      minimumScore: 0
    }),
    createdAt: now
  });
  const overBudgetExclusions = context.exclusions.filter((exclusion) =>
    exclusion.reason === "over_budget" &&
    exclusion.explanation.includes("max inclusion count 1")
  );
  const passed =
    context.inclusions.length === 1 &&
    context.inclusions[0]?.subjectId === "memory-context-primary" &&
    context.inclusions[0]?.expectedUse === "Use this as the selected bounded context item." &&
    overBudgetExclusions.length === 2 &&
    overBudgetExclusions.every((exclusion) =>
      exclusion.subjectId === "memory-context-extra-1" ||
      exclusion.subjectId === "memory-context-extra-2"
    );

  return proof(
    "golden-case-context-roi-001-a",
    passed ? "passed" : "failed",
    passed
      ? "Real ContextROI behavior kept a small packet with expectedUse and explicit over_budget exclusions."
      : "Real ContextROI behavior did not preserve expectedUse or over_budget exclusion evidence."
  );
};

const runObservationPrefixSourceRangeRejection = (now: string): BehaviorFixtureProof => {
  const task = taskContract(
    now,
    "Use observation prefix source range evidence before assembling context."
  );
  const prefix = selectObservationPrefix({
    task,
    projectId: "project-1",
    observations: [observationItem(now, {
      sourceRanges: []
    })],
    maxItems: 1,
    now
  });
  const context = assembleContext({
    id: "context-real-gate-unsourced-prefix",
    harnessPlanId: "plan-real-gate",
    candidates: [],
    observationPrefix: prefix,
    createdAt: now
  });
  const passed =
    context.status === "abstained" &&
    context.observationPrefix === undefined &&
    context.observationPrefixGate?.status === "rejected" &&
    context.observationPrefixGate.reasons.includes("missing_source_ranges") &&
    context.observationPrefixGate.rejectedObservationIds.includes("observation-unsourced-prefix");

  return proof(
    "golden-case-observation-prefix-001-a",
    passed ? "passed" : "failed",
    passed
      ? "Real context assembly rejected selected observation prefix item without source ranges."
      : "Real context assembly did not reject selected observation prefix item without source ranges."
  );
};

const runEvidenceCommandProvenance = (_now: string): BehaviorFixtureProof => {
  const weakDefault = toEvidenceCommandReadback({
    command: "pnpm test",
    status: "not_run"
  });
  const operatorReported = toEvidenceCommandReadback({
    command: "pnpm typecheck",
    status: "passed",
    provenance: "operator_reported",
    exitCode: 0,
    capturedAt: "2026-06-23T10:00:00.000Z",
    assertedBy: "operator"
  });
  const passed =
    weakDefault.provenance === "default_template" &&
    weakDefault.status === "not_run" &&
    weakDefault.doesNotProve.includes("does not prove the command executed") &&
    operatorReported.provenance === "operator_reported" &&
    operatorReported.status === "passed" &&
    operatorReported.doesNotProve.includes("does not prove memory quality");

  return proof(
    "golden-case-evidence-001-a",
    passed ? "passed" : "failed",
    passed
      ? "Real EvidenceBundle behavior distinguishes weak default command rows from operator-reported passed evidence."
      : "Real EvidenceBundle behavior did not preserve command provenance distinction."
  );
};

const runCodexOutputEvidenceShape = (_now: string): BehaviorFixtureProof => {
  const reviewedOutput = validateClaimedCodexOutputEvidence({
    summary: "Implemented the bounded KRN source-search repair from selected context.",
    claimsKrnContextUse: true,
    evidenceRefs: [
      "source_claim:claim-codex-brief-contract",
      "memory_record:memory-context-primary"
    ],
    verification: [
      "pnpm --filter @krn/harness test -- krnBehaviorGate=passed"
    ],
    changedFiles: [
      "packages/harness/src/krn-behavior-gate.ts"
    ],
    doesNotProve: "This output evidence shape does not prove Codex followed every rendered brief section."
  });
  const ungroundedOutput = validateClaimedCodexOutputEvidence({
    summary: "Implemented the task by following KRN context.",
    claimsKrnContextUse: true,
    verification: [
      "pnpm test=passed"
    ],
    changedFiles: [
      "packages/harness/src/krn-behavior-gate.ts"
    ],
    doesNotProve: "This missing-evidence example intentionally lacks evidence refs."
  });
  const overclaimedOutput = validateClaimedCodexOutputEvidence({
    summary: "Implemented the task by following KRN context.",
    claimsKrnContextUse: true,
    evidenceRefs: [
      "source_claim:claim-codex-brief-contract"
    ],
    verification: [
      "pnpm test=passed"
    ],
    changedFiles: [
      "packages/harness/src/krn-behavior-gate.ts"
    ]
  });
  const unverifiedOutput = validateClaimedCodexOutputEvidence({
    summary: "Implemented the task by following KRN context.",
    claimsKrnContextUse: true,
    evidenceRefs: [
      "source_claim:claim-codex-brief-contract"
    ],
    changedFiles: [
      "packages/harness/src/krn-behavior-gate.ts"
    ],
    doesNotProve: "This missing-verification example intentionally lacks command evidence."
  });
  const unscopedChangeOutput = validateClaimedCodexOutputEvidence({
    summary: "Implemented the task by following KRN context.",
    claimsKrnContextUse: true,
    evidenceRefs: [
      "source_claim:claim-codex-brief-contract"
    ],
    verification: [
      "pnpm test=passed"
    ],
    doesNotProve: "This missing-change-list example intentionally lacks changed files."
  });
  const passed =
    reviewedOutput.length === 0 &&
    ungroundedOutput.includes("evidenceRefs are required for claimed KRN output evidence") &&
    overclaimedOutput.includes("doesNotProve is required for claimed KRN output evidence") &&
    unverifiedOutput.includes("verification evidence is required for claimed KRN output evidence") &&
    unscopedChangeOutput.includes("changedFiles are required for claimed KRN output evidence");

  return proof(
    "golden-case-codex-output-evidence-shape-001-a",
    passed ? "passed" : "failed",
    passed
      ? "Real Codex-output evidence-shape gate accepted reviewed evidence refs and rejected KRN-context claims missing evidence refs, verification, changed files, or non-proof."
      : "Codex-output evidence-shape gate did not enforce evidence refs, verification, changed files, and non-proof for claimed KRN context use."
  );
};

const runTargetTrustExclusions = (now: string): BehaviorFixtureProof => {
  const readModel: TargetActivationReadModel = {
    projectKernelId: "kernel-target",
    repoInstallationIds: ["repo-installation-target"],
    localPathHints: ["/tmp/muke-v2"],
    sourceSeeds: [
      {
        path: "evals",
        kind: "eval_workspace",
        reason: "seed eval, acceptance report, and test owner-file recall"
      }
    ],
    trustExclusions: defaultTargetTrustExclusions()
  };
  const recall = buildTargetRecallState(
    now,
    "Repair muke-v2 eval tests and keep target trust exclusions explicit.",
    readModel
  );
  const requiredPatterns = [
    ".env*",
    ".git/",
    "node_modules/",
    ".muke/",
    ".supersearch/runtime/",
    "dist/",
    "build/"
  ];
  const passed =
    recall.hasTrustExclusionCandidate &&
    hasTrustExclusionPatterns(recall.trustExclusionPatterns, requiredPatterns) &&
    hasSourceSeedPath(recall.candidates, "evals") &&
    !recall.staticKrnOwnerFileSelected;

  return proof(
    "golden-case-target-trust-exclusions-001-a",
    passed ? "passed" : "failed",
    passed
      ? "Real target owner-file recall behavior surfaced target source seeds and trust exclusions without selecting static KRN owner files."
      : "Real target owner-file recall behavior did not preserve target trust exclusions or leaked static KRN owner-file candidates."
  );
};

const runTargetFixtureBattleHarness = (now: string): BehaviorFixtureProof => {
  const readModel: TargetActivationReadModel = {
    projectKernelId: "kernel-typescript-basic-fixture",
    repoInstallationIds: ["repo-installation-typescript-basic-fixture"],
    localPathHints: ["tests/fixtures/target-repos/typescript-basic"],
    sourceSeeds: [
      {
        path: "AGENTS.md",
        kind: "agent_guidance",
        reason: "target-local agent instructions and trust boundary"
      },
      {
        path: "README.md",
        kind: "repo_overview",
        reason: "target fixture purpose and setup overview"
      },
      {
        path: "docs",
        kind: "target_runbook",
        reason: "target operator runbook and planning guidance"
      },
      {
        path: "src",
        kind: "source_root",
        reason: "implementation owner-file root"
      },
      {
        path: "tests",
        kind: "test_root",
        reason: "behavior proof and test owner-file root"
      }
    ],
    trustExclusions: defaultTargetTrustExclusions()
  };
  const recall = buildTargetRecallState(
    now,
    "Repair TypeScript fixture tests and source readiness while keeping docs and target trust exclusions explicit.",
    readModel
  );
  const selectedSeedPaths = sourceSeedPaths(recall.candidates);
  const requiredSeedPaths = ["docs", "src", "tests"];
  const requiredPatterns = [".env*", ".muke/", ".supersearch/runtime/", "dist/", "build/"];
  const passed =
    requiredSeedPaths.every((path) => selectedSeedPaths.includes(path)) &&
    recall.hasTrustExclusionCandidate &&
    hasTrustExclusionPatterns(recall.trustExclusionPatterns, requiredPatterns) &&
    !recall.staticKrnOwnerFileSelected;

  return proof(
    "golden-case-target-fixture-battle-001-a",
    passed ? "passed" : "failed",
    passed
      ? "Real target fixture behavior surfaced docs/src/tests source seeds and trust exclusions without selecting static KRN owner files."
      : "Real target fixture behavior did not preserve fixture source seeds, trust exclusions, or target-scoped owner-file recall."
  );
};

const runTargetOwnerFileBelowRoots = (now: string): BehaviorFixtureProof => {
  const readModel: TargetActivationReadModel = {
    projectKernelId: "kernel-typescript-basic-fixture",
    repoInstallationIds: ["repo-installation-typescript-basic-fixture"],
    localPathHints: ["tests/fixtures/target-repos/typescript-basic"],
    sourceSeeds: [
      {
        path: "src",
        kind: "source_root",
        reason: "implementation owner-file root"
      },
      {
        path: "tests",
        kind: "test_root",
        reason: "behavior proof and test owner-file root"
      }
    ],
    ownerFiles: [
      {
        path: "src/index.ts",
        root: "src",
        kind: "implementation_entry",
        reason: "implementation readiness owner file"
      },
      {
        path: "tests/readiness.test.ts",
        root: "tests",
        kind: "behavior_test",
        reason: "test readiness owner file"
      }
    ],
    trustExclusions: [
      {
        pathPattern: ".env*",
        reason: "secret-shaped environment files must not enter planning context"
      }
    ]
  };
  const candidates = buildOwnerFileRecallCandidates(
    taskContract(now, "Repair TypeScript fixture readiness test owner file."),
    { targetReadModel: readModel }
  );
  const targetOwnerFileCandidate = candidates.find((candidate) =>
    candidate.metadata.targetReadModelKind === "owner_file" &&
    candidate.metadata.targetPath === "tests/readiness.test.ts"
  );
  const staticKrnOwnerFileSelected = candidates.some((candidate) =>
    candidate.metadata.source === "owner_file_recall"
  );
  const passed =
    targetOwnerFileCandidate !== undefined &&
    targetOwnerFileCandidate.reason === "Target owner file: tests/readiness.test.ts" &&
    targetOwnerFileCandidate.expectedUse.includes("tests/readiness.test.ts") &&
    !staticKrnOwnerFileSelected;

  return proof(
    "golden-case-target-owner-file-below-roots-001-a",
    passed ? "passed" : "failed",
    passed
      ? "Real target owner-file recall surfaced a bounded owner file below tests/ without selecting static KRN owner files."
      : "Real target owner-file recall did not surface the bounded owner file below named target roots."
  );
};

const runDecorativeSourceRejection = (_now: string): BehaviorFixtureProof => {
  const decorativeClaim = sourceClaim({
    id: "source-claim-decorative",
    claim: "This source should be retained because it sounds useful.",
    mechanism: "",
    krnImplication: "",
    doesNotProve: "",
    supportType: "background",
    consumer: "",
    falsifier: ""
  });
  const signals = assessSourceClaimReviewSignals(decorativeClaim);
  const passed =
    signals.some((signal) =>
      signal.kind === "missing_source_to_decision_fields" &&
      signal.severity === "blocking"
    ) &&
    signals.some((signal) =>
      signal.kind === "decorative_support_type" &&
      signal.severity === "blocking"
    );

  return proof(
    "golden-case-source-decorative-rejection-001-a",
    passed ? "passed" : "failed",
    passed
      ? "Real source review behavior blocked decorative source retention when source-to-decision fields and decision-grade support were missing."
      : "Real source review behavior did not block decorative source retention."
  );
};

const sourceArtifactPreviewHash = (content: string): string =>
  `golden-hash:${content.length}:${content.slice(0, 12)}`;

interface SourceArtifactPreviewReuseCandidate {
  claimCandidate: ExtractionClaimCandidate | undefined;
  relationCount: number;
  activationCandidate: ActivationCandidate | undefined;
}

const buildSourceArtifactPreviewReuseCandidate = (): SourceArtifactPreviewReuseCandidate => {
  const artifact = [
    "# Source Artifact Preview Reuse",
    "",
    "KRN should prove one bounded local ingest loop before building a crawler.",
    "",
    "This source artifact preview evidence supports later source search readback."
  ].join("\n");
  const chunks = buildSourceArtifactPreviewChunks({
    lines: sourceArtifactLines(artifact),
    chunkSize: 20,
    limit: 2,
    contentHash: sourceArtifactPreviewHash,
    maxPreviewCharacters: 240
  });
  const extraction = extractLocalSourceCandidates(chunks);
  const claimCandidate = extraction.claims.find((candidate) =>
    candidate.text.includes("bounded local ingest loop")
  );

  if (claimCandidate === undefined) {
    return {
      claimCandidate,
      relationCount: extraction.relations.length,
      activationCandidate: undefined
    };
  }

  return {
    claimCandidate,
    relationCount: extraction.relations.length,
    activationCandidate: toSourceClaimCandidate(sourceClaim({
      id: "source-claim-artifact-preview-reuse",
      claim: claimCandidate.text,
      mechanism: "A local source artifact preview can become a reviewable SourceClaim candidate with a source range.",
      krnImplication: "Reuse the previewed local ingest-loop claim as bounded source activation context before crawler work.",
      doesNotProve: "This does not prove crawler readiness, source truth, DB persistence, embeddings, or ranking quality.",
      supportType: "implementation-boundary",
      consumer: "source artifact preview reuse behavior gate",
      metadata: {
        source: "source_artifact_preview",
        extractionCandidateId: claimCandidate.id,
        extractionCandidateSourceRange: claimCandidate.sourceRange
      }
    }))
  };
};

const assembleSourceArtifactPreviewReuseContext = (
  now: string,
  activationCandidate: ActivationCandidate
) => assembleContext({
  id: "context-real-gate-source-artifact-preview-reuse",
  harnessPlanId: "plan-real-gate",
  candidates: applyContextROI(
    applyActivationFilters({
      candidates: rankCandidates(
        [activationCandidate],
        buildSourceQuery(taskContract(
          now,
          "Use bounded local ingest-loop evidence before building crawler work."
        ))
      ),
      antiMemoryRecords: [],
      minimumSourceAuthority: "low",
      now
    }).candidates,
    {
      maxInclusions: 1,
      minimumScore: 0,
      minimumDiverseKinds: ["source"]
    }
  ),
  createdAt: now
});

const provesSourceArtifactPreviewReuse = (now: string): boolean => {
  const reuseCandidate = buildSourceArtifactPreviewReuseCandidate();

  if (reuseCandidate.claimCandidate?.reviewability !== "ready") {
    return false;
  }

  if (reuseCandidate.relationCount <= 0 || reuseCandidate.activationCandidate === undefined) {
    return false;
  }

  const context = assembleSourceArtifactPreviewReuseContext(
    now,
    reuseCandidate.activationCandidate
  );

  return context.status === "assembled" && context.inclusions.some((inclusion) =>
    inclusion.subjectType === "source_claim" &&
    inclusion.subjectId === "source-claim-artifact-preview-reuse"
  );
};

const runSourceArtifactPreviewReuse = (now: string): BehaviorFixtureProof => {
  const passed = provesSourceArtifactPreviewReuse(now);

  return proof(
    "golden-case-source-artifact-preview-reuse-001-a",
    passed ? "passed" : "failed",
    passed
      ? "Real source artifact preview extraction produced a reviewable claim that shaped later source activation context."
      : "Real source artifact preview extraction did not produce a reviewable reusable source activation claim."
  );
};

const runRelationGroundedQaReadback = (now: string): BehaviorFixtureProof => {
  const seed = sourceClaim({
    id: "source-claim-graph-qa-seed",
    claim: "Graph QA should answer from explicit source relations.",
    mechanism: "The seed claim defines the question but does not include the answer.",
    krnImplication: "Use it as the relation seed for relation-grounded QA readback."
  });
  const answer = sourceClaim({
    id: "source-claim-graph-qa-answer",
    claim: "Relation-grounded QA answer comes from the edge-connected source claim.",
    mechanism: "A reviewed SourceClaimEdge connects the seed claim to this answer claim.",
    krnImplication: "Use this selected claim to ground the tiny graph QA answer."
  });
  const lexicalOnly = sourceClaim({
    id: "source-claim-graph-qa-lexical-only",
    claim: "Graph QA should remain bounded and avoid platform expansion.",
    mechanism: "This claim matches graph QA terms but has no answer relation.",
    krnImplication: "Use as a no-relation baseline competitor."
  });
  const edge: SourceClaimEdge = {
    id: "source-claim-edge-graph-qa-answer",
    fromSourceClaimId: seed.id,
    toSourceClaimId: answer.id,
    kind: "supports",
    metadata: {
      consumer: "golden relation-grounded QA readback",
      evidenceRef: "packages/harness/src/krn-behavior-gate.ts",
      doesNotProve: "This edge does not prove graph QA quality."
    },
    createdAt: now
  };
  const query = buildSourceQuery(taskContract(
    now,
    "Answer graph QA from relation-grounded source context."
  ));
  const baselineContext = assembleContext({
    id: "context-real-gate-graph-qa-baseline",
    harnessPlanId: "plan-real-gate",
    candidates: applyContextROI(rankCandidates([
      {
        ...toSourceClaimCandidate(seed),
        lexicalScore: 5
      },
      {
        ...toSourceClaimCandidate(answer),
        lexicalScore: 15
      },
      {
        ...toSourceClaimCandidate(lexicalOnly),
        lexicalScore: 35
      }
    ], query), { maxInclusions: 1 }),
    createdAt: now
  });
  const edgeAwareContext = assembleContext({
    id: "context-real-gate-graph-qa-edge-aware",
    harnessPlanId: "plan-real-gate",
    candidates: applyContextROI(rankCandidates(
      applySourceClaimEdgeInfluence([
        {
          ...toSourceClaimCandidate(seed),
          lexicalScore: 5
        },
        {
          ...toSourceClaimCandidate(answer),
          lexicalScore: 15
        },
        {
          ...toSourceClaimCandidate(lexicalOnly),
          lexicalScore: 35
        }
      ], {
        edges: [edge],
        seedSourceClaimIds: [seed.id],
        now,
        graphScore: 30
      }),
      query
    ), { maxInclusions: 1 }),
    createdAt: now
  });
  const readback = buildRelationGroundedQaReadback({
    baselineContext,
    edgeAwareContext,
    sourceClaims: [seed, answer, lexicalOnly],
    answerSourceClaimId: answer.id
  });
  const passed =
    readback.outcome === "improved" &&
    readback.baseline.verdict === "insufficient" &&
    readback.edgeAware.verdict === "grounded" &&
    readback.edgeAware.usedSourceClaimIds.includes(answer.id) &&
    readback.doesNotProve.includes("production graph retrieval quality");

  return proof(
    "golden-case-graph-qa-001-a",
    passed ? "passed" : "failed",
    passed
      ? "Real relation-grounded QA readback showed baseline insufficient and edge-aware context grounded the answer."
      : "Real relation-grounded QA readback did not preserve the baseline-vs-edge answer delta."
  );
};

const proofFactories = {
  "golden-case-memory-smoke-001": runStaleMemoryAbstention,
  "golden-case-memory-smoke-002": runAntiMemoryBlock,
  "golden-case-reflection-001-a": runReflectionNonCandidateTargetBlock,
  "golden-case-memory-005-a": runRawRecallExactProof,
  "golden-case-context-roi-001-a": runContextRoiBoundary,
  "golden-case-observation-prefix-001-a": runObservationPrefixSourceRangeRejection,
  "golden-case-evidence-001-a": runEvidenceCommandProvenance,
  "golden-case-target-fixture-battle-001-a": runTargetFixtureBattleHarness,
  "golden-case-target-owner-file-below-roots-001-a": runTargetOwnerFileBelowRoots,
  "golden-case-target-trust-exclusions-001-a": runTargetTrustExclusions,
  "golden-case-source-decorative-rejection-001-a": runDecorativeSourceRejection,
  "golden-case-source-artifact-preview-reuse-001-a": runSourceArtifactPreviewReuse,
  "golden-case-graph-qa-001-a": runRelationGroundedQaReadback,
  "golden-case-codex-output-evidence-shape-001-a": runCodexOutputEvidenceShape
} as const;

type SupportedCaseId = keyof typeof proofFactories;

const isSupportedCaseId = (caseId: string): caseId is SupportedCaseId =>
  caseId in proofFactories;

export const runKrnBehaviorGate = (
  input: RunKrnBehaviorGateInput
): BehaviorFixtureRunReport => {
  const caseIds = new Set(
    input.tasks.flatMap((task) => task.cases.map((behaviorCase) => behaviorCase.id))
  );
  const proofs = [...caseIds].flatMap((caseId) =>
    isSupportedCaseId(caseId) ? [proofFactories[caseId](input.now)] : []
  );

  return runBehaviorFixtures({
    tasks: input.tasks,
    proofs
  });
};
